### ISSUE TITLE
使用者無法修改暱稱

### ISSUE THREAD

**Issue by manlinglee** [peter1421/drf_admin#13]
# Bug回報

## 簡述
- 管理員可以新增修改刪除使用者的暱稱
- 但是使用者無法自己修改暱稱，欄位預設格式還是電話號碼

## 預期行為
- 

## 實際行為
- 看下面影片
- 管理員介面可以 而且正常
- 但後半段切到個人中心就不能存了

## 截圖(非必填)

https://github.com/peter1421/drf_admin/assets/44687554/4d37bd0f-054f-42c8-8441-2afe52fc10ac

## 環境(非必填)
- 操作系統：[例如 iOS]
- 瀏覽器：[例如 Chrome, Safari]
- 版本：[例如 22]

## 備註(非必填)
- 在這裡添加任何其他上下文關於問題的描述

**Comment by peter1421** [comment]
@manlinglee  已完成 請在網頁上確認
![](https://i.imgur.com/W3ecYUa.png)
![](https://i.imgur.com/8sajYtV.png)
