### ISSUE TITLE
上次的聊天紀錄不出現在本次聊天

### ISSUE THREAD

**Issue by zong-1220** [peter1421/drf_admin#18]
# 功能要求

## 功能概述
- 新增重整對話按鈕

## 使用案例
- 結束聊天時，能點下按鈕，結束對話，進到下一個對話紀錄中

## 用戶界面/設計(非必填)
- 簡要說明任何用戶界面變更或設計要求

## 技術要求(非必填)
- 列出實現此功能所需的主要技術考量或依賴

**Comment by peter1421** [comment]
@webber0928 
目前master的現有原理

1.創機器人時，會自動新增紀錄id
![](https://i.imgur.com/LjOVMvg.png)
2.新增id後加到now_chatroom_id (表示現在機器人使用這個聊天紀錄)
![](https://i.imgur.com/DisVRXH.png)
3.傳訊息:依照now_chatroom_id 更新到chatroom_id 
4.抓訊息:依照now_chatroom_id 找chatroom_id
![](https://i.imgur.com/NM1TZKW.png)

參考作法:
按下按鈕後，新增一個紀錄id，並更新now_chatroom_id
每次傳訊息跟抓訊息，開啟第二個chatroom_id，舊的chatroom_id就不會出現了
完成功能

**Comment by peter1421** [comment]
補充 當前聊天效果
![](https://i.imgur.com/iAs5ern.png)

**Comment by webber0928** [comment]
![截圖 2024-02-15 凌晨4 53 22](https://github.com/peter1421/drf_admin/assets/7552785/dc495b77-eed1-449e-a3de-7ae10d33073c)

畫面如圖所示，按下按鈕可以結束這次的對話。

**Comment by peter1421** [comment]
@webber0928 
離開對話功能正常

但有bug
註冊新帳號後，創立書籍機器人時會失敗

要再修改一下
我這幾天幫你修看看 
![image](https://github.com/peter1421/drf_admin/assets/51041311/c76ceb89-d52e-44f2-9bd4-1cd563d36ab5)
