### ISSUE TITLE
使用者資訊

### ISSUE THREAD

**Issue by manlinglee** [peter1421/drf_admin#8]
![IMG_0526](https://github.com/peter1421/drf_admin/assets/44687554/cd68bd09-2af5-4d39-9962-87dec33b53d7)
應該不用存手機號碼 儀表板要暱稱 跟真實姓名分開 感謝

**Comment by zong-1220** [comment]
![image](https://github.com/peter1421/drf_admin/assets/79858190/4daad9f3-074b-4aea-8b3c-89ca2fcf979d)
修改了 但資料庫應該有把輸入系統鎖住,輸入正常電話格式也不可以，應該是大陸那邊的格式，把性別的資料庫也不行，
版面修改了，但剩下資料庫存入的問題

**Comment by manlinglee** [comment]
![image](https://github.com/peter1421/drf_admin/assets/44687554/c7775b3f-ea70-4eed-8e38-02d78b3645ae)
是不是跟這邊有關

**Comment by zong-1220** [comment]
![1706627072748](https://github.com/peter1421/drf_admin/assets/79858190/ee239845-cd50-43f6-8f08-66015a51672a)
使用者在自我編輯個人資料與後台欄位幫他們建資料庫的欄位對不齊，可能要重新與資料庫對過

**Comment by peter1421** [comment]
跟issue#13重複
